version: '3'
services:
  neo4j:
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - 9090:7474
      - 7687:7687
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: "neo4j/neo4jpassword"
      NEO4J_initial_dbms_default__database: "graphcontact"